Master ef
SemyonTolkachyov/QoodenTask pull request #1
Opened 2023-07-28 12:58 UTC by SemyonTolkachyov

2023-07-28 15:24 UTC, efpies requested changes

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Controllers/WalletController.cs
> +            tx = await balanceService.DepositFiat(userId,
Можно и так, но сервис балансов становится слишком громоздким (теперь он знает про валидацию запросов, знает про фиат и крипто, хотя его задача — работать с балансами) + для депозитов может добавиться дополнительная логика.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Controllers/WalletController.cs
> +        if (depositModel is DepositFiatModel depositFiatModel)
Оператор is предназначен для проверки, является ли объект наследником интерфейса или какого-то класса. У тебя body парсится в `BaseDepositModel`, потому ни одна ветка if не будет работать, `tx` всегда будет `null`.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/BalanceService.cs
> +    /*public async Task<Dictionary<string, UserBalance>> GetBalance(int userId)
Много комментированного кода.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/BalanceService.cs
> +        foreach (var currency in await _currencyService.GetCurrencies())
Это можно заменить на LINQ.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +    private int _rateDelay { get; set; }
Что такое rate delay? В каких единицах он измеряется? Наносекунды? Дни? Недели? Либо надо добавлять суффикс, либо в конфигурацию класть `TimeSpan`.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +        _rateDelay = Convert.ToInt32(configuration["RateDelay"]);
Опции должны быть `IOptions`, напрямую секции читать в сервисах не стоит, т. к. это тяжело поддерживать, тяжело тестировать, добавляет лишнее знание в сервис и т. д.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +    private Random _random { get; set; }
Если поле не будет переинициализироваться, можно просто `private readonly Random _random = new()`

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/MigrationService.cs
> +                if (migration.SourceType == MigrationSourceTypeEnum.Json)
Разработчику не даётся никакого уведомления о том, что если вдруг попался тип миграции, для которого нет обработчика, то надо что-то с этим делать. В таком случае данная проблема будет незамеченной.

2023-07-28 15:24 UTC, efpies commented on QoodenTask/Services/MigrationService.cs
> +            if (await dbContext.Migrations.CountAsync() < 1)
Count < 1 можно заменить на !Any

2023-08-04 13:27 UTC, efpies requested changes

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Services/RateService.cs
> +            currentRates.Rates.Add(currency.Id, (decimal)lastCurrencyRate);
lastCurrencyRate.Value

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Program.cs
> +}
А чем старый формат Program не угодил?

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Services/DepositeService.cs
> +public class DepositeService : IDepositeService
Deposit

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Services/DepositeService.cs
> +        if (currency.Type != "Fiat") return null;
Логично сделать currency.Type enum-ом

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Services/DepositeService.cs
> +        var tx = new Transaction
В транзакции должно быть больше информации, т. к. в будущем может потребоваться аудит и т. д., поэтому нужно добавить информацию об адресах, картах и т. д.

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Services/DepositeService.cs
> +            Currency = currency
User логично переместить вверх, а Amount и Currency будут рядом. Проще читать, когда код по смыслу группируется.

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Services/DepositeService.cs
> +        if (currency.Type != "Crypto") return null;
Кажется, это — не очень нормальная ситуация, когда на неправильный тип currency приходит неправильная модель. Тут надо не null возвращать, а ошибку бросать.

2023-08-04 13:27 UTC, efpies commented on QoodenTask/Models/UserDto.cs
> +    //public Dictionary<string, decimal> Balances { get; set; }
Комментированный код.

2023-08-16 06:08 UTC, SemyonTolkachyov commented on QoodenTask/Entities/User.cs
> +            if (value == "Admin")
https://github.com/SemyonTolkachyov/QoodenTask/commit/b8086b2edb79802ceea9818390a23b1fc9583682
исправил

2023-08-16 06:11 UTC, SemyonTolkachyov commented on QoodenTask/Services/UserService.cs
> +        if (user != null)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/1da1c8defc3edcc406652b970ef9ef1dcec5009c#diff-3ee98a2b863fde348fc26fd8a4a29d1aa3dbc6e7098b89544ff1499a5996fa93

2023-08-16 06:12 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/WalletController.cs
> +        if (depositModel is DepositFiatModel depositFiatModel)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/1da1c8defc3edcc406652b970ef9ef1dcec5009c

2023-08-16 06:21 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +        foreach (var currency in await _currencyService.GetCurrencies())
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e27928bff210d5e5f5d77453ee2c6a7fcd6ba92d

2023-08-17 06:12 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/WalletController.cs
> +        var userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimsIdentity.DefaultNameClaimType)?.Value);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/64aabf4875af4caf09fdff227db3acfffc685341

2023-08-17 06:18 UTC, SemyonTolkachyov commented on QoodenTask/Services/TransactionService.cs
> +    public async Task<Transaction?> ChangeStatusTx(Transaction tx, TransactionStatus newStatus)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/c8fcd64409782f0a586fd3949d96d1e336560f0b

2023-08-17 06:22 UTC, SemyonTolkachyov commented on QoodenTask/Models/UserDto.cs
> +    //public Dictionary<string, decimal> Balances { get; set; }
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/a75fe601641fe15d56fb7cecff6d3c0dd61042da

2023-08-18 05:56 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositeService.cs
> +public class DepositeService : IDepositeService
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/98434f56a855e6eabd39502b9a33f2a0b0f022cf

2023-08-18 05:56 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositeService.cs
> +        if (currency.Type != "Fiat") return null;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/98434f56a855e6eabd39502b9a33f2a0b0f022cf

2023-08-18 05:56 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositeService.cs
> +        var tx = new Transaction
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/98434f56a855e6eabd39502b9a33f2a0b0f022cf

2023-08-18 05:56 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositeService.cs
> +        var currency = await _currencyService.GetCurrency(currencyId);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/98434f56a855e6eabd39502b9a33f2a0b0f022cf

2023-08-18 05:56 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositeService.cs
> +        if (currency.Type != "Crypto") return null;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/98434f56a855e6eabd39502b9a33f2a0b0f022cf

2023-08-20 15:07 UTC, efpies requested changes

2023-08-20 15:07 UTC, efpies commented on QoodenTask/Services/BalanceService.cs
> +        if (user is { Balances: not { } })
Можно писать `if (user is { Balances: null })`

2023-08-20 15:07 UTC, efpies commented on QoodenTask/Services/BalanceService.cs
> +            );
Можно писать currencies?.ForEach(currency => { balances.Add(currency.Id, new UserBalance()); });

2023-08-20 15:07 UTC, efpies commented on QoodenTask/Controllers/WalletController.cs
> +        if (tx is not { })
tx is null

2023-09-13 05:51 UTC, SemyonTolkachyov commented on QoodenTask/Common/Constants.cs
> +public static class Constants
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/c4666d281c036cdbaa9e671cd6c60b0d354c83d7

2023-09-13 05:52 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/AuthController.cs
> +        userService.ChangePassword(user,newPass);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/cb760c5fa8c86f51dea33ee5991d07122d949cb9

2023-09-13 05:52 UTC, SemyonTolkachyov commented on QoodenTask/Services/UserService.cs
> +        return id == await _dbContext.Users.Where(u => u.Id == id && (includeBlocked || u.IsActive)).Select(u => u.Id).SingleOrDefaultAsync();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/333595c1d00c0f5993f1e609b35d510039cd43d2

2023-09-13 05:54 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/RatesController.cs
> +        if (currentRates is null)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/96bd0977a2d55cb9a3f0d3d6ddcf5df8b47eb430

2023-09-13 05:57 UTC, SemyonTolkachyov commented on QoodenTask/ServiceInterfaces/IDepositeService.cs
> +public interface IDepositeService
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/8071e23f519f34d7d28db895f94f51c867edd933

2023-09-13 05:58 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositService.cs
> +        await _dbContext.SaveChangesAsync();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/9674ddbf4c2c48f4a3bc2b28499575b4c372e2ff

2023-09-13 05:58 UTC, SemyonTolkachyov commented on QoodenTask/Services/UserService.cs
> +    public async Task<User?> Create(UserDto userDto, string role = Constants.User)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:58 UTC, SemyonTolkachyov commented on QoodenTask/Services/TransactionService.cs
> +    public async Task<List<Transaction>?> GetTxsByStatus(TransactionStatus status)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:58 UTC, SemyonTolkachyov commented on QoodenTask/Services/TransactionService.cs
> +    public async Task<List<Transaction>?> GetTxs()
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:58 UTC, SemyonTolkachyov commented on QoodenTask/Services/RateService.cs
> +                    currentRates.Rates.Add(currency.Id, (decimal)lastCurrencyRate);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:58 UTC, SemyonTolkachyov commented on QoodenTask/Services/MigrationService.cs
> +                }
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:59 UTC, SemyonTolkachyov commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +                _exchangeData.RateHistory.Add(new CurrencyRate()
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:59 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +            if (user is { Role: "Admin" }) return null;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:59 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +        var balances = await _dbContext.Balances.Where(b => b.UserId == user.Id).ToListAsync();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:59 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +        if (user is { Balances: not { } })
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:59 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +                (decimal)(balance.Amount * _rateService.GetCurrentRate(balance.Currency.Id));
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 05:59 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +    public async Task<Dictionary<string, UserBalance>?> GetBalance(int userId)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 06:00 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +            var userBalances = await GetUserBalances(user);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e3ca45bb5682bbabb96e9a1ebe0574cbdb883000

2023-09-13 06:00 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +            );
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6d23b768394beef0f9dc3f7c45eb5202653ee249

2023-09-13 06:01 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/WalletController.cs
> +        if (tx is not { })
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/2551ef245d99b96d0d611d0a26cc1e438c8bd549

2023-09-17 16:50 UTC, efpies requested changes

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Services/UserService.cs
> +    public async Task<User?> Create(UserDto userDto, string role = Constants.User)
Ниже есть метод SetRole с такой же проблемой

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Services/BalanceService.cs
> +        if (user is { Balances: not { } })
Всё ещё выгребаются.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Controllers/AdminUserController.cs
> +    [Authorize(Roles = Roles.Admin)]
Все методы доступны только из-под Admin, потом это можно вынести в аннотацию над контроллером.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Controllers/AdminWalletController.cs
> +    [Authorize(Roles = Roles.Admin)]
Можно вынести в аннотацию над контроллером.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Controllers/AuthController.cs
> +[Authorize]
Этот атрибут не нужен, если ты на каждый метод его вешаешь.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Controllers/WalletController.cs
> +        if (tx is null)
это всё можно сделать внутри try, тогда не придётся создавать переменную Transaction? вне try-catch.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Controllers/WalletController.cs
> +    [Authorize(Roles = Roles.User)]
Все методы — для user, потому можно вынести.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Services/DepositService.cs
> +        else if (depositModel is DepositCryptoModel depositCryptoModel)
Проблема была в дублировании кода, но фикс объединением в 1 — так себе. Нужно их грамотно распилить обратно на 2. У них могут быть какие-то общие вещи, они должны быть в базовом классе. В остальном они могут идти разными путями, т. к. фиат и крипта работают по-разному.

2023-09-17 16:50 UTC, efpies commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +                    currencies = (List<Currency>?)await currencyService.GetCurrencies();
IList мы возвращаем, т. к. там может быть и массив, и list. Если вернётся массив, этот каст упадёт. Соответственно, надо обойтись без каста.

2023-09-17 16:54 UTC, SemyonTolkachyov commented on QoodenTask/Program.cs
> +}
Что бы использовать в проекте тестов, класс должен быть публичным

2023-09-18 06:29 UTC, SemyonTolkachyov commented on QoodenTask/Services/UserService.cs
> +    public async Task<User?> Create(UserDto userDto, string role = Constants.User)
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:29 UTC, SemyonTolkachyov commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +                _exchangeData.RateHistory.Add(new CurrencyRate()
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:29 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +        if (user is { Balances: not { } })
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:30 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +            currencies.ForEach(currency => { balances.Add(currency.Id, new UserBalance()); }
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:30 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/WalletController.cs
> +        if (tx is null)
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:31 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositService.cs
> +        else if (depositModel is DepositCryptoModel depositCryptoModel)
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:31 UTC, SemyonTolkachyov commented on QoodenTask/Services/ExchangeRateGenerator.cs
> +                    currencies = (List<Currency>?)await currencyService.GetCurrencies();
исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3d10b03f625fb5be8e70dbba289c8b144e7109a8

2023-09-18 06:31 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/WalletController.cs
> +    [Authorize(Roles = Roles.User)]
Не все, поэтому удалил только аннотацию над контроллером
https://github.com/SemyonTolkachyov/QoodenTask/commit/03480f87281c1005dba7e5ed2d1a916e7369fa4a

2023-09-18 06:32 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/AuthController.cs
> +[Authorize]
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/03480f87281c1005dba7e5ed2d1a916e7369fa4a

2023-09-18 06:32 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/AdminWalletController.cs
> +    [Authorize(Roles = Roles.Admin)]
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/03480f87281c1005dba7e5ed2d1a916e7369fa4a

2023-09-18 06:32 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/AdminUserController.cs
> +    [Authorize(Roles = Roles.Admin)]
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/03480f87281c1005dba7e5ed2d1a916e7369fa4a

2023-09-19 06:03 UTC, efpies commented on QoodenTask.Client/main.js
> +const baseUrl = 'https://localhost:44390'
С хоста http://localhost:63342/ не работают запросы.

2023-09-19 17:42 UTC, SemyonTolkachyov commented on QoodenTask/QoodenTask.csproj
> +      <_ContentIncludedByDefault Remove="Shared\TransactionData\AdminTransactionsDataGrip.razor" />
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6b3412e82ea7555938b533cc1d856727a525c177

2023-09-19 17:43 UTC, SemyonTolkachyov commented on QoodenTask/Program.cs
> +}
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6b3412e82ea7555938b533cc1d856727a525c177

2023-09-19 17:43 UTC, SemyonTolkachyov commented on QoodenTask/Controllers/WalletController.cs
> +                return NotFound(currencyId);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d553ed83fa4ebe843937fa50b68c9dc3940c7fde

2023-09-19 17:44 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +        balances = currencies?.ToDictionary(c => c.Id , _ => new UserBalance());
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d553ed83fa4ebe843937fa50b68c9dc3940c7fde

2023-09-19 17:44 UTC, SemyonTolkachyov commented on QoodenTask/Services/BalanceService.cs
> +            user.Balances = await GetUserBalances(user) as List<Balance>;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d553ed83fa4ebe843937fa50b68c9dc3940c7fde

2023-09-19 17:44 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositService.cs
> +        if (tx.Currency.Type != CurrencyType.Fiat) throw new Exception("Incorrect currency type");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d553ed83fa4ebe843937fa50b68c9dc3940c7fde

2023-09-19 17:44 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositService.cs
> +        var currency = await _currencyService.GetCurrency(currencyId);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d553ed83fa4ebe843937fa50b68c9dc3940c7fde

2023-09-20 06:50 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +            alert("Wrong login or password");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/9b8e31c8ffe024075a0bbc72faed6b6575b26be8

2023-09-20 06:50 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +function onSubmit(e) {
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/9b8e31c8ffe024075a0bbc72faed6b6575b26be8

2023-09-20 15:45 UTC, efpies requested changes

2023-09-20 15:45 UTC, efpies commented on QoodenTask.Client/main.js
> +            $(signUpForm).hide();
Логику лучше вынести в отдельный метод, чтобы не раздувать колбэки.

2023-09-20 15:45 UTC, efpies commented on QoodenTask.Client/main.js
> +            alert("Sign-up failed");
Сервер возвращает ошибки регистрации. Их надо показывать.

2023-09-20 15:45 UTC, efpies commented on QoodenTask/Services/DepositService.cs
> +        var currency = await _currencyService.GetCurrency(currencyId);
Мы прошли полный круг и вернулись в изначальную точку) Попробуй распилить на 2 сервиса с одним базовым.

2023-09-20 15:45 UTC, efpies commented on QoodenTask.Client/main.js
> +const baseUrl = 'https://localhost:44390'
Нужно слать на https://localhost:7271

2023-09-20 15:45 UTC, efpies commented on QoodenTask.Client/main.js
> +    console.log(formData);
После регистрации почему-то 403, потом всё норм. Надо выяснить, откуда 403.

2023-09-20 15:45 UTC, efpies commented on QoodenTask.Client/main.js
> +signUpForm.addEventListener("submit", onSignUp);
Нужна кнопка логаута.

2023-09-20 15:45 UTC, efpies commented on QoodenTask.Client/main.js
> +            alert("Login failed");
При логине с несуществующими логином-паролем выдаётся ошибка 500, т. к. сервак падает.

2023-09-20 18:40 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositService.cs
> +        var currency = await _currencyService.GetCurrency(currencyId);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/8c6e11e2dbf350dc3b1ff00d4a38c128a66b068d

2023-09-21 11:54 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +            $(signUpForm).hide();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e34bc77984b73447098b3bc57d99ee4ba95f7a7c

2023-09-21 11:54 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +            alert("Sign-up failed");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e34bc77984b73447098b3bc57d99ee4ba95f7a7c

2023-09-21 11:54 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +const baseUrl = 'https://localhost:44390'
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e34bc77984b73447098b3bc57d99ee4ba95f7a7c

2023-09-21 11:54 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +    console.log(formData);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e34bc77984b73447098b3bc57d99ee4ba95f7a7c

2023-09-21 11:54 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +            alert("Login failed");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e34bc77984b73447098b3bc57d99ee4ba95f7a7c

2023-09-21 11:55 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +const baseUrl = 'https://localhost:44390'
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/e34bc77984b73447098b3bc57d99ee4ba95f7a7c

2023-09-21 11:56 UTC, SemyonTolkachyov commented on QoodenTask/Services/DepositService.cs
> +        var currency = await _currencyService.GetCurrency(currencyId);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/8c6e11e2dbf350dc3b1ff00d4a38c128a66b068d

2023-09-21 13:06 UTC, efpies commented on QoodenTask.Client/main.js
> +            alert("Login failed");
Не исправлено

2023-09-21 13:07 UTC, efpies commented on QoodenTask.Client/main.js
> +    console.log(formData);
Не исправлено. После регистрации юзера вызывается /admin/users, а он недоступен пользователю.

2023-09-21 13:10 UTC, efpies commented on QoodenTask.Client/main.js
> +            alert("Sign-up failed");
Имелись в виду ошибки валидации при регистрации. Оказывается, у тебя её вообще нет. А должна быть. В задании юзернейм и пароль 4-8 символов.

2023-09-21 13:11 UTC, efpies commented on QoodenTask.Client/main.js
> +const baseUrl = 'https://localhost:44390'
Всё ещё не работают: в CORS прописан 63344.

2023-09-21 13:13 UTC, efpies requested changes

2023-09-21 13:13 UTC, efpies commented on QoodenTask.Client/main.js
> +SetDefaultVisibility();
Cookie никак не используется. При обновлении страницы логин пропадает. Юзер должен оставаться залогиненным.

2023-09-21 13:13 UTC, efpies commented on QoodenTask.Client/main.js
> +            alert("Login failed");
При логине админа тоже 500.

2023-09-22 05:52 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +const baseUrl = 'https://localhost:44390'
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/684c80fcc6f1838ab3f9f01771bea39269b66a6b

2023-09-22 05:53 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +            alert("Sign-up failed");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/684c80fcc6f1838ab3f9f01771bea39269b66a6b

2023-09-22 05:53 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +    console.log(formData);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/684c80fcc6f1838ab3f9f01771bea39269b66a6b

2023-09-22 05:53 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +            alert("Login failed");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/684c80fcc6f1838ab3f9f01771bea39269b66a6b

2023-09-22 05:53 UTC, SemyonTolkachyov commented on QoodenTask.Client/main.js
> +SetDefaultVisibility();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/684c80fcc6f1838ab3f9f01771bea39269b66a6b

2023-09-22 10:54 UTC, merged