Tests
SemyonTolkachyov/QoodenTask pull request #3
Opened 2023-09-24 12:26 UTC by SemyonTolkachyov

2023-09-24 14:23 UTC, efpies requested changes

2023-09-24 14:23 UTC, efpies commented on QoodenTask.Tests/WalletControllerTest.cs
> +            CookieContainer cookies = new CookieContainer();
HttpClient умеет сохранять куки самостоятельно, для этого не надо ничего делать с заголовками и CookieContainer.

2023-09-24 14:23 UTC, efpies commented on QoodenTask.Tests/WalletControllerTest.cs
> +            var loginResponse = await _client.PostAsync("auth/login", content);
Слишком много кода вокруг логина повторяется во всех тестах.

2023-09-24 14:23 UTC, efpies commented on QoodenTask.Tests/WalletControllerTest.cs
> +            var content = JsonContent.Create(new LoginDto
Можно пользоваться PostAsJsonAsync, тогда не надо будет писать везде JsonContent.Create.

2023-09-25 11:28 UTC, SemyonTolkachyov commented on QoodenTask.Tests/WalletControllerTest.cs
> +            var content = JsonContent.Create(new LoginDto
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/74406755670c663557edcdae03e46f34482f877e

2023-09-25 11:28 UTC, SemyonTolkachyov commented on QoodenTask.Tests/WalletControllerTest.cs
> +            var loginResponse = await _client.PostAsync("auth/login", content);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/74406755670c663557edcdae03e46f34482f877e

2023-09-25 11:28 UTC, SemyonTolkachyov commented on QoodenTask.Tests/WalletControllerTest.cs
> +            CookieContainer cookies = new CookieContainer();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/74406755670c663557edcdae03e46f34482f877e

2023-09-25 11:28 UTC, SemyonTolkachyov commented on QoodenTask/QoodenTask.csproj
> +
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/74406755670c663557edcdae03e46f34482f877e

2023-09-25 11:28 UTC, SemyonTolkachyov commented on QoodenTask/Program.cs
> +
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/74406755670c663557edcdae03e46f34482f877e

2023-09-26 11:24 UTC, efpies requested changes

2023-09-26 11:24 UTC, efpies commented on QoodenTask/Models/TransactionDto.cs
> +    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
Эта DTO заполняется данными из другого класса, тут не должно быть дефолтных данных и какой-то логики.

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/Extensions/HttpClientTestExtensions.cs
> +    public static async Task<HttpResponseMessage?> Login(this HttpClient client, AppDbContext dbContext, string username, string password)
В тестах не должно быть понимания, как устроено хранение юзеров. Да и вообще нигде не должно быть. Нужно следовать принципу разделения ответственности. Задача этого метода — залогиниться с юзернеймом и паролем. О том, как юзера хранятся и как их получать, знает UserService и AuthController. А тут ты, по сути, дублируешь логику о том, как найти юзера в таблице и делаешь 50% работы метода логина.

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/BaseTest.cs
> +    protected HttpClient? m_client;
protected-поля — это плохо, т. к. жизнью начинают управлять внешние классы, а данный класс не может отловить поведение. https://stackoverflow.com/questions/3182653/are-protected-members-fields-really-that-bad

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/BaseTest.cs
> +                        c.AddDbContextFactory<AppDbContext>(
Предлагаю перевести на InMemoryDatabase https://learn.microsoft.com/en-us/ef/core/providers/in-memory/ Тогда не придётся поднимать в докере.

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/Services/UserServiceTest.cs
> +        {
Можно убрать фигурные скобки, уменьшив вложенность кода.

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/Services/UserServiceTest.cs
> +            users!.Count.Should().Be(2);
Лучше писать `users!.ShouldHaveCount(2)`, чтобы не завязываться на имплементацию count в конкретном контейнере, а также для другого сообщения об ошибке.

2023-09-26 11:24 UTC, efpies commented on QoodenTask/ServiceInterfaces/IUserService.cs
>      public Task<IList<User>?> GetAll();
Как тут вообще может прийти null?

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/Services/TransactionServiceTest.cs
> +            txs!.Count.Should().Be(2);
Мало получить транзакции, надо ещё и получить правильные транзакции. То есть те, которые ты положил. Это надо проверять.

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +            if (loginResponse is { StatusCode: HttpStatusCode.OK })
Задача теста: получить список юзеров.
1. Взять залогиненный клиент.
2. Отправить запрос на получение юзеров.
3. Проверить ответ

В тесте не должно быть подобных условий. Проверка логина не относится к данному тесту

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/AuthControllerTest.cs
> +            response!.StatusCode.Should().Be(HttpStatusCode.OK);
Что мы проверяем в данном тесте? Если код не ОК, то проверить, что код ОК. Это как должно работать?

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/AuthControllerTest.cs
> +        var response = await m_client.PostAsJsonAsync("auth/login", new LoginDto
У тебя уже есть метод extension для логина.

2023-09-26 11:24 UTC, efpies commented on QoodenTask.Tests/AuthControllerTest.cs
> +        var user = await m_dbContext.Users.FirstOrDefaultAsync(u => u.UserName == "AdmTest" && u.Password == "admTest");
В данном тесте мы не должны проверять, что юзер есть в БД. Ты либо создаёшь его в setup, либо создаёшь его тут. Но задача этого теста — не проверка наличия юзера в БД.

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AuthControllerTest.cs
> +        var user = await m_dbContext.Users.FirstOrDefaultAsync(u => u.UserName == "AdmTest" && u.Password == "admTest");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AuthControllerTest.cs
> +        var response = await m_client.PostAsJsonAsync("auth/login", new LoginDto
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AuthControllerTest.cs
> +            response!.StatusCode.Should().Be(HttpStatusCode.OK);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +            if (loginResponse is { StatusCode: HttpStatusCode.OK })
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Services/TransactionServiceTest.cs
> +            txs!.Count.Should().Be(2);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask/ServiceInterfaces/IUserService.cs
>      public Task<IList<User>?> GetAll();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Services/UserServiceTest.cs
> +            users!.Count.Should().Be(2);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:27 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Services/UserServiceTest.cs
> +        {
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:28 UTC, SemyonTolkachyov commented on QoodenTask.Tests/BaseTest.cs
> +    protected HttpClient? m_client;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:28 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Extensions/HttpClientTestExtensions.cs
> +    public static async Task<HttpResponseMessage?> Login(this HttpClient client, AppDbContext dbContext, string username, string password)
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 06:28 UTC, SemyonTolkachyov commented on QoodenTask/Models/TransactionDto.cs
> +    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d8534313bf6e05d3c8283a21a77e606c57cf4d67

2023-09-27 19:00 UTC, efpies requested changes

2023-09-27 19:00 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        user.Transactions.Add(new Transaction()
На уровне контроллера мы уже пишем не unit-тесты, а интеграционные, т. к. они тестируют уровень выше. А раз так, то лучше сделать этот тест полностью интеграционным, проверяя реальный сценарии взаимодействия. Т. е. транзакции надо вставлять не руками в базу, а создавать с помощью API. Точно так же не лазать тут в конекст вообще, всё делать через API.

2023-09-27 19:00 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var tx = await Context.Transactions.FirstOrDefaultAsync(t =>
Нужна проверка на то, сколько транзакций ожидается. А то вдруг будет 0, тест упадёт с exception.

2023-09-27 19:00 UTC, efpies commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        blockedUser!.IsActive.Should().Be(false);
BeFalse().

2023-09-27 19:00 UTC, efpies commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        response.Should().HaveStatusCode(HttpStatusCode.OK);
Получили юзера, в нём написано слово из 3 букв. Статус success, а в ответе — мусор. Надо проверять содержимое ответа.

2023-09-27 19:00 UTC, efpies commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        await Client.Login(1, "admTest");
Везде повторяется 1 admTest, нужно вынести хелпер

2023-09-28 18:56 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        await Client.Login(1, "admTest");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d045af2b91e72338f64cc94aa2a591969b1c6381

2023-09-28 18:56 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        response.Should().HaveStatusCode(HttpStatusCode.OK);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/5dd891aa54e331894ce69e13cebf7986b6b8043e

2023-09-28 18:57 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        blockedUser!.IsActive.Should().Be(false);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/5dd891aa54e331894ce69e13cebf7986b6b8043e

2023-09-28 18:59 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var tx = await Context.Transactions.FirstOrDefaultAsync(t =>
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/5dd891aa54e331894ce69e13cebf7986b6b8043e

2023-09-28 19:00 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        user.Transactions.Add(new Transaction()
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/6a2b0f836452990cafe2984f3701a57cee221699

2023-09-28 19:01 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        Context = await DbContextFactory.CreateDbContextAsync();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/5dd891aa54e331894ce69e13cebf7986b6b8043e

2023-09-28 19:01 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        else tx.Should().NotBeNull();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/3a64c8564f02b746f2b1a055c0b9da657450639f

2023-09-28 20:11 UTC, efpies requested changes

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        users!.FirstOrDefault(u => u.UserName == DefaultUserData.AdminUsername).Should().NotBeNull();
Нужно проверять и содержимое объекта тоже.

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/Services/TransactionServiceTest.cs
> +        txs!.FirstOrDefault(t => t.CurrencyId =="ethTest")!.Amount.Should().Be(1);
А если такой currency в txs нет, то всё упадёт. Правильней будет:
1. получить currency
2. проверить, что она есть
3. проверить её amount

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        txs!.FirstOrDefault(t => t.CurrencyId == ethTest.Id && t.UserId == user!.Id && t.Amount == 55).Should().NotBeNull();
Такой assertion нам даст, что у нас такой объект не найден. А нам нужно проверять, что у объекта нужные поля, это будет давать другую ошибку.

Правильней будет:
1. Проверить, что есть только 1 транзакция
2. Взять её.
3. проверять каждое поле отдельным assert-ом.

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var txs = JsonConvert.DeserializeObject<List<Transaction>>(await balancesResponse.Content.ReadAsStringAsync());
Можно вынести хелпер для HttpResponse, который бы занимался десериализацией.

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var user = await Context.Users.FirstOrDefaultAsync(u => u.UserName == DefaultUserData.UserUsername
Везде повторяется этот код.

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        await Client.PostAsJsonAsync("wallet/deposit/ethTest", depositModel);
Это нужно вынести как хелперы для HttpClient вместо посылания голых запросов в тесте.

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        Client = ApplicationFactory!.CreateClient();
Мне кажется, создание клиента и контекста можно вынести в Setup

2023-09-28 20:11 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        Context.Transactions.AsNoTracking().ToList().Should().HaveCount(1);
В интеграционных тестах работаем с API. Например, пользователь может получать транзакции или админ.

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminUserControllerTest.cs
> +        users!.FirstOrDefault(u => u.UserName == DefaultUserData.AdminUsername).Should().NotBeNull();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        Context.Transactions.AsNoTracking().ToList().Should().HaveCount(1);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        Client = ApplicationFactory!.CreateClient();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        await Client.PostAsJsonAsync("wallet/deposit/ethTest", depositModel);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var user = await Context.Users.FirstOrDefaultAsync(u => u.UserName == DefaultUserData.UserUsername
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var txs = JsonConvert.DeserializeObject<List<Transaction>>(await balancesResponse.Content.ReadAsStringAsync());
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        txs!.FirstOrDefault(t => t.CurrencyId == ethTest.Id && t.UserId == user!.Id && t.Amount == 55).Should().NotBeNull();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 10:23 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Services/TransactionServiceTest.cs
> +        txs!.FirstOrDefault(t => t.CurrencyId =="ethTest")!.Amount.Should().Be(1);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/d497507176d30ce12428f1dab29bf02bbd4a3708

2023-10-01 11:44 UTC, efpies requested changes

2023-10-01 11:44 UTC, efpies commented on QoodenTask.Tests/Extensions/HttpClientTestExtensions.cs
> +        => JsonConvert.DeserializeObject<T>(await httpResponseMessage.Content.ReadAsStringAsync())!;
Эта длинная конструкция заменяется на ReadFromJsonAsync

2023-10-01 11:44 UTC, efpies commented on QoodenTask.Tests/Services/UserServiceTest.cs
> +        users.FirstOrDefault(u => u.UserName == "AdmTest").Should().NotBeNull();
Можно заменить на `users.Should().ContainSingle(<action>)`

2023-10-01 11:44 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var tx = txs.FirstOrDefault();
если у тебя count > 0, то FirstOrDefault не нужен, можно просто First, тогда проверок на null не надо будет.

2023-10-01 11:44 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        tx.Address.Should().Be("2323244234244322");
Почему именно такие поля? Тому, кто читает тест, непонятно. Сверяться нужно с тем, что отсылаешь. Потому метод DepositDefaultCrypto нужно заменить на DepositCrypto, а также сделать статический запрос DefaultDepositCrypto, который везде передавать, и с которым сверяться.

2023-10-01 11:44 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        tx.UserId.Should().Be(user.Id);
Проверяются не все поля. Например, какой статус должен быть у вновь созданной транзакции?

2023-10-01 11:44 UTC, efpies commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        await Client!.DepositDefaultCrypto("ethTest");
У тебя currency создана, потому не надо хардкодить тут эту строку, её наддо брать из currency.

2023-10-01 14:46 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        await Client!.DepositDefaultCrypto("ethTest");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/fd6cf647f0f82d9c2de8dc00869f9fb35cc3eb83

2023-10-01 14:46 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        tx.UserId.Should().Be(user.Id);
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/fd6cf647f0f82d9c2de8dc00869f9fb35cc3eb83

2023-10-01 14:46 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        tx.Address.Should().Be("2323244234244322");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/fd6cf647f0f82d9c2de8dc00869f9fb35cc3eb83

2023-10-01 14:46 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var tx = txs.FirstOrDefault();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/fd6cf647f0f82d9c2de8dc00869f9fb35cc3eb83

2023-10-01 14:46 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Services/UserServiceTest.cs
> +        users.FirstOrDefault(u => u.UserName == "AdmTest").Should().NotBeNull();
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/fd6cf647f0f82d9c2de8dc00869f9fb35cc3eb83

2023-10-01 14:46 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Extensions/HttpClientTestExtensions.cs
> +        => JsonConvert.DeserializeObject<T>(await httpResponseMessage.Content.ReadAsStringAsync())!;
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/fd6cf647f0f82d9c2de8dc00869f9fb35cc3eb83

2023-10-01 16:00 UTC, efpies requested changes

2023-10-01 17:22 UTC, SemyonTolkachyov commented on QoodenTask.Tests/AdminWalletControllerTest.cs
> +        var txs = await Client!.DeserializeJsonFromResponse<List<Transaction>>(await Client!.GetAsync($"admin/wallets/tx"));
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/7854819fa97aaeb1b83432c54c4f6b69a65934d6

2023-10-01 17:22 UTC, SemyonTolkachyov commented on QoodenTask.Tests/Services/TransactionServiceTest.cs
> +        Context!.Currencies.Should().ContainSingle(c => c.Id == "ethTest");
Исправлено в https://github.com/SemyonTolkachyov/QoodenTask/commit/7854819fa97aaeb1b83432c54c4f6b69a65934d6

2023-10-02 15:10 UTC, merged